services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    restart: unless-stopped
    ulimits:
      memlock: -1
    environment:
      DFLY_requirepass: ${CACHE_PASSWORD}
    ports:
      - "${CACHE_PORT}:6379"
    volumes:
      - dragonfly_data:/data

volumes:
  psql_volume:
  dragonfly_data:
