/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DirectorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isDeleted', 'moduleType', 'ownerId', 'positionIdx', 'title', 'updatedAt'] as const
  $columns = DirectorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDeleted: boolean
  @column()
  declare moduleType: string | null
  @column()
  declare ownerId: string
  @column()
  declare positionIdx: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EnvironmentSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'id', 'name', 'ownerId', 'updatedAt'] as const
  $columns = EnvironmentSchema.$columns
  @column()
  declare avatar: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare ownerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NoteSchema extends BaseModel {
  static $columns = ['content', 'cover', 'createdAt', 'directoryId', 'id', 'isDeleted', 'ownerId', 'positionIdx', 'rawContent', 'title', 'updatedAt'] as const
  $columns = NoteSchema.$columns
  @column()
  declare content: string | null
  @column()
  declare cover: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare directoryId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDeleted: boolean
  @column()
  declare ownerId: string
  @column()
  declare positionIdx: number
  @column()
  declare rawContent: any | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'displayName', 'email', 'id', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
